services:

  elasticsearch:
    image: elasticsearch:8.16.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      somenetwork:
        aliases:
          - somenetwork.elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.16.4
    container_name: kibana
    networks:
      somenetwork:
        aliases:
          - somenetwork.kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  somenetwork: